insert into country
    (name, iso_2, iso_3, iso_numeric, show_on_ui, auto_reject)
values ('Cyprus', 'CY', 'CYP', 196, TRUE, FALSE),
       ('Ukraine', 'UA', 'UKR', 804, TRUE, TRUE),
       ('France', 'FR', 'FRA', 250, TRUE, TRUE),
       ('Spain', 'ES', 'ESP', 724, TRUE, TRUE),
       ('Sweden', 'SE', 'SWE', 752, TRUE, TRUE),
       ('Germany', 'DE', 'DEU', 276, TRUE, TRUE),
       ('Finland', 'FI', 'FIN', 246, TRUE, TRUE),
       ('Norway', 'NO', 'NOR', 578, TRUE, TRUE),
       ('Poland', 'PL', 'POL', 616, TRUE, TRUE),
       ('Italy', 'IT', 'ITA', 380, TRUE, TRUE),
       ('United Kingdom', 'GB', 'GBR', 826, TRUE, TRUE),
       ('Romania', 'RO', 'ROU', 642, TRUE, TRUE),
       ('Belarus', 'BY', 'BLR', 112, TRUE, TRUE),
       ('Greece', 'GR', 'GRC', 300, TRUE, TRUE),
       ('Bulgaria', 'BG', 'BGR', 100, TRUE, TRUE),
       ('Iceland', 'IS', 'ISL', 352, TRUE, TRUE),
       ('Portugal', 'PT', 'PRT', 620, TRUE, TRUE),
       ('Czech Republic', 'CZ', 'CZE', 203, TRUE, TRUE),
       ('Denmark', 'DK', 'DNK', 208, TRUE, TRUE),
       ('Hungary', 'HU', 'HUN', 348, TRUE, TRUE),
       ('Serbia', 'RS', 'SRB', 688, TRUE, TRUE),
       ('Austria', 'AT', 'AUT', 40, TRUE, TRUE),
       ('Ireland', 'IE', 'IRL', 372, TRUE, TRUE),
       ('Lithuania', 'LT', 'LTU', 440, TRUE, TRUE),
       ('Latvia', 'LV', 'LVA', 428, TRUE, TRUE),
       ('Croatia', 'HR', 'HRV', 191, TRUE, TRUE),
       ('Bosnia and Herzegovina', 'BA', 'BIH', 70, TRUE, TRUE),
       ('Slovakia', 'SK', 'SVK', 703, TRUE, TRUE),
       ('Estonia', 'EE', 'EST', 233, TRUE, TRUE),
       ('Netherlands', 'NL', 'NLD', 528, TRUE, TRUE),
       ('Switzerland', 'CH', 'CHE', 756, TRUE, TRUE),
       ('Moldova', 'MD', 'MDA', 498, TRUE, TRUE),
       ('Belgium', 'BE', 'BEL', 56, TRUE, TRUE),
       ('Albania', 'AL', 'ALB', 8, TRUE, TRUE),
       ('Macedonia', 'MK', 'MKD', 807, TRUE, TRUE),
       ('Slovenia', 'SI', 'SVN', 705, TRUE, TRUE),
       ('Montenegro', 'ME', 'MNE', 499, TRUE, TRUE),
       ('Luxembourg', 'LU', 'LUX', 442, TRUE, TRUE),
       ('Faroe Is.', 'FO', 'FRO', 234, TRUE, TRUE),
       ('Andorra', 'AD', 'AND', 20, TRUE, TRUE),
       ('Malta', 'MT', 'MLT', 470, TRUE, TRUE),
       ('Liechtenstein', 'LI', 'LIE', 438, TRUE, TRUE),
       ('Guernsey', 'GG', 'GGY', 831, TRUE, TRUE),
       ('San Marino', 'SM', 'SMR', 674, TRUE, TRUE),
       ('Gibraltar', 'GI', 'GIB', 292, TRUE, TRUE),
       ('Monaco', 'MC', 'MCO', 492, TRUE, TRUE),
       ('Vatican City', 'VA', 'VAT', 336, TRUE, TRUE)
;
